[2024-03-29 15:55:18,944][regelum][INFO] - Saved summary to /home/matvey/portfolio_opt_regelum/regelum_data/outputs/2024-03-29/15-55-15/0/SUMMARY.html. (175ms)
[2024-03-29 15:55:18,981][regelum][INFO] - Script terminated with error.
[2024-03-29 15:55:18,982][regelum][ERROR] - object of type 'numpy.float64' has no len()
Traceback (most recent call last):
  File "/home/matvey/.pyenv/versions/3.9.16/envs/regelum/lib/python3.9/site-packages/regelum/__init__.py", line 947, in app
    res = old_app(ccfg)
  File "/home/matvey/portfolio_opt_regelum/run.py", line 6, in launch
    scenario.run()  # run it
  File "/home/matvey/.pyenv/versions/3.9.16/envs/regelum/lib/python3.9/site-packages/regelum/scenario.py", line 473, in run
    return super().run()
  File "/home/matvey/.pyenv/versions/3.9.16/envs/regelum/lib/python3.9/site-packages/regelum/scenario.py", line 140, in run
    self.run_episode(
  File "/home/matvey/.pyenv/versions/3.9.16/envs/regelum/lib/python3.9/site-packages/regelum/scenario.py", line 410, in run_episode
    super().run_episode(
  File "/home/matvey/.pyenv/versions/3.9.16/envs/regelum/lib/python3.9/site-packages/regelum/scenario.py", line 156, in run_episode
    self.sim_status = self.step()
  File "/home/matvey/.pyenv/versions/3.9.16/envs/regelum/lib/python3.9/site-packages/regelum/scenario.py", line 190, in step
    self.action = self.compute_action_sampled(
  File "/home/matvey/.pyenv/versions/3.9.16/envs/regelum/lib/python3.9/site-packages/regelum/__internal/base.py", line 30, in new_method
    res = method(self2, *args, **kwargs)
  File "/home/matvey/portfolio_opt_regelum/src/scenario.py", line 69, in compute_action_sampled
    return super().compute_action_sampled(time, estimated_state, observation)
  File "/home/matvey/.pyenv/versions/3.9.16/envs/regelum/lib/python3.9/site-packages/regelum/scenario.py", line 238, in compute_action_sampled
    self.compute_action(
  File "/home/matvey/.pyenv/versions/3.9.16/envs/regelum/lib/python3.9/site-packages/regelum/__internal/base.py", line 30, in new_method
    res = method(self2, *args, **kwargs)
  File "/home/matvey/.pyenv/versions/3.9.16/envs/regelum/lib/python3.9/site-packages/regelum/scenario.py", line 560, in compute_action
    self.optimize(Event.compute_action)
  File "/home/matvey/.pyenv/versions/3.9.16/envs/regelum/lib/python3.9/site-packages/regelum/scenario.py", line 566, in optimize
    self.issue_action(self.data_buffer.get_latest("observation"))
  File "/home/matvey/.pyenv/versions/3.9.16/envs/regelum/lib/python3.9/site-packages/regelum/scenario.py", line 266, in _issue_action
    self.on_action_issued(observation)
  File "/home/matvey/.pyenv/versions/3.9.16/envs/regelum/lib/python3.9/site-packages/regelum/scenario.py", line 542, in on_action_issued
    received_data = super().on_action_issued(observation)
  File "/home/matvey/.pyenv/versions/3.9.16/envs/regelum/lib/python3.9/site-packages/regelum/scenario.py", line 269, in on_action_issued
    self.current_running_objective = self.running_objective(
  File "/home/matvey/.pyenv/versions/3.9.16/envs/regelum/lib/python3.9/site-packages/regelum/objective.py", line 73, in __call__
    running_objective = self.model(observation, action)
  File "/home/matvey/portfolio_opt_regelum/src/objective.py", line 16, in __call__
    number_of_stocks = (len(observation[0]) - 1)//2
TypeError: object of type 'numpy.float64' has no len()
[2024-03-29 15:55:19,006][regelum][INFO] - Saved callbacks to /home/matvey/portfolio_opt_regelum/regelum_data/outputs/2024-03-29/15-55-15/0/callbacks.dill. (0ms)
